#!/usr/bin/env python3
"""
Mock LLM Server for Development
Provides OpenAI-compatible API endpoints for testing without vLLM
"""

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import json
import time
import uuid
from datetime import datetime

app = FastAPI(title="Mock LLM Server", version="1.0.0")

class ChatMessage(BaseModel):
    role: str
    content: str

class ChatCompletionRequest(BaseModel):
    model: str = "microsoft/DialoGPT-small"
    messages: List[ChatMessage]
    temperature: Optional[float] = 0.7
    max_tokens: Optional[int] = 1000
    stream: Optional[bool] = False

class ChatCompletionResponse(BaseModel):
    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: List[Dict[str, Any]]
    usage: Dict[str, int]

class EmbeddingRequest(BaseModel):
    model: str = "text-embedding-ada-002"
    input: str

class EmbeddingResponse(BaseModel):
    object: str = "list"
    data: List[Dict[str, Any]]
    model: str
    usage: Dict[str, int]

@app.get("/health")
async def health_check():
    """Health check endpoint"""
    return {
        "status": "healthy",
        "timestamp": datetime.now().isoformat(),
        "service": "mock-llm-server"
    }

@app.get("/v1/models")
async def list_models():
    """List available models"""
    return {
        "object": "list",
        "data": [
            {
                "id": "microsoft/DialoGPT-small",
                "object": "model",
                "created": int(time.time()),
                "owned_by": "mock-server"
            },
            {
                "id": "text-embedding-ada-002",
                "object": "model",
                "created": int(time.time()),
                "owned_by": "mock-server"
            }
        ]
    }

@app.post("/v1/chat/completions")
async def chat_completions(request: ChatCompletionRequest):
    """Mock chat completion endpoint"""
    
    # Extract the last user message
    user_message = ""
    for message in reversed(request.messages):
        if message.role == "user":
            user_message = message.content
            break
    
    # Generate a mock response
    mock_responses = {
        "hello": "Hello! I'm a mock AI assistant. How can I help you today?",
        "help": "I'm here to help! I can answer questions, provide information, and assist with various tasks.",
        "ai": "Artificial Intelligence (AI) is a branch of computer science that aims to create systems capable of performing tasks that typically require human intelligence.",
        "machine learning": "Machine Learning is a subset of AI that enables computers to learn and improve from experience without being explicitly programmed.",
        "rag": "Retrieval-Augmented Generation (RAG) is a technique that combines information retrieval with text generation to provide more accurate and contextual responses."
    }
    
    # Find the best matching response
    response = "I understand you're asking about something. Let me provide a helpful response based on your query."
    user_message_lower = user_message.lower()
    
    for key, value in mock_responses.items():
        if key in user_message_lower:
            response = value
            break
    
    # Add some context if it's a general question
    if "?" in user_message and response == "I understand you're asking about something. Let me provide a helpful response based on your query.":
        response = f"Based on your question: '{user_message}', here's what I can tell you. This is a mock response for development purposes. In a real system, this would be generated by an actual language model."
    
    return ChatCompletionResponse(
        id=f"chatcmpl-{uuid.uuid4().hex}",
        created=int(time.time()),
        model=request.model,
        choices=[
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": response
                },
                "finish_reason": "stop"
            }
        ],
        usage={
            "prompt_tokens": len(user_message.split()),
            "completion_tokens": len(response.split()),
            "total_tokens": len(user_message.split()) + len(response.split())
        }
    )

@app.post("/v1/embeddings")
async def embeddings(request: EmbeddingRequest):
    """Mock embedding endpoint"""
    
    # Generate mock embeddings (random vectors)
    import random
    embedding_dim = 768  # Standard embedding dimension
    
    # Create a deterministic embedding based on input text
    random.seed(hash(request.input) % 2**32)
    embedding = [random.uniform(-1, 1) for _ in range(embedding_dim)]
    
    return EmbeddingResponse(
        data=[
            {
                "object": "embedding",
                "embedding": embedding,
                "index": 0
            }
        ],
        model=request.model,
        usage={
            "prompt_tokens": len(request.input.split()),
            "total_tokens": len(request.input.split())
        }
    )

@app.get("/")
async def root():
    """Root endpoint"""
    return {
        "message": "Mock LLM Server",
        "version": "1.0.0",
        "endpoints": [
            "/health",
            "/v1/models",
            "/v1/chat/completions",
            "/v1/embeddings"
        ]
    }

if __name__ == "__main__":
    import uvicorn
    print("🚀 Starting Mock LLM Server...")
    print("📊 Available endpoints:")
    print("   - Health: http://localhost:8001/health")
    print("   - Models: http://localhost:8001/v1/models")
    print("   - Chat: http://localhost:8001/v1/chat/completions")
    print("   - Embeddings: http://localhost:8001/v1/embeddings")
    print()
    
    uvicorn.run(app, host="0.0.0.0", port=8001) 